[package]
name = "rust-os"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[profile.dev]
panic = "abort"
opt-level = "s" # 对应 -Os
codegen-units = 1
lto = true

[profile.release]
panic = "abort"
opt-level = "s" # 对应 -Os
codegen-units = 1
lto = true